### ISSUE TITLE
MY NIGGA CRIES IRL TO DISCORD BAITS LELKEK

### ISSUE THREAD

**Issue by RealzPrestige** [gerald0mc/Mint-LEAKED-0.1.1#6]

**Comment by fortnitegodpro** [comment]
Dear konas Devs,

Watermark:

Add modes: Text - Image - Both

New Mode: Both -> This makes it so instead of just the watermark or the text, it displays both of those.

Nametags:

NO LAG MY FPS GO POOPOO AND I HAVE TO USE CREEPY SAL >:(

ReverseStep:

Glitches when you are going down 3 or more blocks, my pyro one works fine but idk

**Comment by fortnitegodpro** [comment]
Hello please fix I spent my birthday money on this

**Comment by ProfKambing** [comment]
OMG I CRIED SO HARD WHEN GETTING BAITED BY ZPRESTIGE WAAAAA

**Comment by gerald0mc** [comment]
> OMG I CRIED SO HARD WHEN GETTING BAITED BY ZPRESTIGE WAAAAA
OMG I CRIED SO HARD WHEN GETTING BAITED BY ZPRESTIGE WAAAAA
